### ISSUE TITLE
Inquiry on Implementation Strategy, Differences from CARLA Scenario Runner, and OpenSCENARIO Compatibility

### ISSUE THREAD

**Issue by Kagura-0001** [basiclab/TTSG#1]
Hello,

Firstly, fantastic work on the project; it’s truly impressive!

I’m interested in understanding the implementation strategy you’ve adopted. Could you share some insights into the methodologies used?

Also, how does this differ from the CARLA Scenario Runner? And is there compatibility with OpenSCENARIO?

Looking forward to your insights.

**Comment by Justin900429** [comment]
Hi,

Thank you for your interest in our work!

As you pointed out, our rendering interface differs from Scenario Runner in a few ways:
1. Different input formats
2. Various options for controlling the agent
3. Support for random road selection

To bridge the gap, we are planning to add Scenario Runner support to facilitate the integration of our work into other projects.

Regarding OpenSCENARIO, it should be somewhat compatible with our system since it shares some overlap with the OpenDRIVE format. However, we haven't tested it yet.

I hope this helps! 😄
